### PR TITLE
SessionConfig: Make http_only cookie option configurable

### PR DESCRIPTION
**Pull request by DominicWrege**
see: #80

### CODE REVIEW

**Comment by maxcountryman** [comment]
Hi, thank you for the PR. Before we merge this, I want to understand the use case a little more. There is a security concern should this not remain HttpOnly.

**Comment by DominicWrege** [comment]
Hi my use case simple. I have a JavaScript frontend and need access to the cookie value without using some kind of JWT stuff.

I understand the possible security concern but that why it's by default true. 

If think this is an advanced option that should exist and this decision should be made by the developer not the library/framework.

Maybe we can add a note to the docs: something "Caution the cookie can be read by JavaScript"

**Comment by DominicWrege** [comment]
@maxcountryman  I updated the docs.

> Configures the "HTTP-Only" attribute of the cookie used for the session.
> For security reasons the default value is true.
> If this attribute is false, it indicates that the cookie is vulnerable to being accessed by JavaScript, thus posing a significant risk for potential XSS (Cross-Site Scripting) attacks.

**Comment by maxcountryman** [comment]
Amazing. Thank you! 🙏

**Pull request merged**
