### PR TITLE
update http crate

### PR DESCRIPTION
**Pull request by maxcountryman**
This also updates axum-core to ensure compatibility.

### CODE REVIEW

**Comment by cole-h** [comment]
In case it's useful, I also attempted a http bump here: https://github.com/cole-h/tower-sessions/tree/support-axum-0.7 (specifically, in this commit: https://github.com/cole-h/tower-sessions/commit/22ddd61cf59ab617582bd2090b64c3971f6323a0)

Note that this is blocked on https://github.com/imbolc/tower-cookies/pull/30 being released.

**Comment by maxcountryman** [comment]
Thanks for that @cole-h.

It looks like layers also behave differently in axum 0.7 as `type Service = CookieManager<SessionManager<S, Store>>` is not compiling, complaining with:

```
the trait `Service<http::Request<Body>>` is not implemented for `HandleError<tower_cookies::service::CookieManager<SessionManager<Route, MemoryStore>>, {closure@examples/counter.rs:19:38: 19:51}, _>
```

I'm a bit confused.

**Comment by cole-h** [comment]
OK, I've updated my branch with the tower-cookies v0.10.0 bump as well: https://github.com/cole-h/tower-sessions/commit/d21adec41ba9c8b166486ca96d229dd076d1d788

Everything should work now!

**Comment by maxcountryman** [comment]
@cole-h fantastic! Happy to merge in your branch if you like.

**Comment by cole-h** [comment]
Sure thing! I opened https://github.com/maxcountryman/tower-sessions/pull/107.

Note that it also includes a not-quite-necessary commit setting `reqwest` to use the `rustls` feature -- happy to drop that if you like, but it made it possible for me to run the tests and whatnot without setting up `pkg-config` (the default features of `reqwest` try to link against `openssl`).

**Pull request closed without merging**
