### PR TITLE
only delete from stores when we have a cookie

### PR DESCRIPTION
**Pull request by maxcountryman**
If we don't have a cookie, the session is new and therefore has never been saved. Given this, we should not invoke the overhead of talking to the store. Likewise, we don't need to set a removal cookie as we have never set the cookie.

This should address the original issue in #89.

### CODE REVIEW

**Comment by maxcountryman** [comment]
This could also check that we have a loaded session, either from the store or the in-memory cache that's used for safe concurrent data access; this might be more correct because a malicious user agent could send along a bogus session ID, which would invoke the overhead of talking to the store.

**Comment by bikeshedder** [comment]
I can confirm that this fixes the superfluous `Storage::delete` calls. It still does log "created new session" and "deleted" though.

**Review by bikeshedder — APPROVED** [review]

**Comment by DominicWrege** [comment]
Can't wait to get this merged :)

**Comment by maxcountryman** [comment]
Thanks for taking a look. I'll cut a new release shortly.

**Pull request merged**
